### ISSUE TITLE
problem with last openfl?

### ISSUE THREAD

**Issue by francescoagati** [player-03/advanced-layout#1]
I get this error with last openfl

```
/usr/lib/haxe/lib/advanced-layout/git/layout/item/TextSize.hx:42: characters 2-38 : Float should be Null<Int>
/usr/lib/haxe/lib/advanced-layout/git/layout/item/TextSize.hx:42: characters 2-38 : Float should be Int
```

**Comment by player-03** [comment]
Apparently they switched to integer-based text size. This should now be fixed.

**Comment by francescoagati** [comment]
yes  works with openfl and also with nme

**Comment by vrescobar** [comment]
Hi that's still happening to me, and I think I have latest version from openfl:

advanced-layout: [0.4.1]
layout: [1.2.1]
openfl: 3.0.1 3.0.2 3.0.6 3.0.8 3.3.1 [3.3.3]

Any idea about how to solve that?

**Comment by player-03** [comment]
I hadn't actually uploaded this fix to Haxelib. Try updating it now.
